# -*- coding: utf-8 -*-
"""Movie_Genre_Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lmq3opQ4c9gEC07_ZGOzh7sfMdvQGzNi

**MOVIE GENRE CLASSIFICATION** ---- **(TASK 1 FOR MACHINE LEARNING)**

**FEB Batch P33 CODSOFT INTERNSHIP PROGRAM**

<h1 style="font-family: 'poppins'; font-weight: bold; color: Green;">👨💻Author: Irfan Ullah Khan</h1>

[![GitHub](https://img.shields.io/badge/GitHub-Profile-blue?style=for-the-badge&logo=github)](https://github.com/programmarself)
[![Kaggle](https://img.shields.io/badge/Kaggle-Profile-blue?style=for-the-badge&logo=kaggle)](https://www.kaggle.com/programmarself)
[![LinkedIn](https://img.shields.io/badge/LinkedIn-Profile-blue?style=for-the-badge&logo=linkedin)](https://www.linkedin.com/in/irfan-ullah-khan-4a2871208/)  

[![YouTube](https://img.shields.io/badge/YouTube-Profile-red?style=for-the-badge&logo=youtube)](https://www.youtube.com/@irfanullahkhan7748)
[![Email](https://img.shields.io/badge/Email-Contact%20Me-red?style=for-the-badge&logo=email)](mailto:programmarself@gmail.com)
[![Website](https://img.shields.io/badge/Website-Contact%20Me-red?style=for-the-badge&logo=website)](https://datasciencetoyou.odoo.com/)
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""**Load Dataset**"""

df = pd.read_csv("movies_genres.csv", delimiter='\t')

"""**Information about Dataset**"""

df.info()

"""**Size of Dataset**"""

df.shape

"""**First 5 Rows of Dataset**"""

df.head()

"""**Last 5 Rows of Dataset**"""

df.tail()

"""We have a total of 47403 movies and each of them is associated with 28 possible genres. The genres columns simply contain a 1 or 0 depending of wether the movie is classified into that particular genre or not, so the one-hot-enconding schema is alreay provided in this file.

**Next we are going to calculate the absolute number of movies per genre**

Note: each movie can be associated with more than one genre, we just want to know which genres have more movies.
"""

df_genres = df.drop(['plot', 'title'], axis=1)
counts = []
categories = list(df_genres.columns.values)
for i in categories:
    counts.append((i, df_genres[i].sum()))
df_stats = pd.DataFrame(counts, columns=['genre', '#movies'])
df_stats

df_stats.plot(x='genre', y='#movies', kind='bar', legend=False, grid=True, figsize=(15, 8))

"""Since the `Lifestyle` has 0 instances we can just remove it from the data set"""

df.drop('Lifestyle', axis=1, inplace=True)

"""One thing that notice when working with this dataset is that there are plots written in different languages. Let's use [langedetect](https://pypi.python.org/pypi/langdetect?) tool to identify the language in which the plots are written"""

!pip install langdetect
from langdetect import detect

df['plot_lang'] = df['plot'].apply(lambda text: detect(str(text)))
print(df['plot_lang'].value_counts())

"""There other languages besides English, let's just keep English plots, and save this to a new file."""

df = df[df.plot_lang.isin(['en'])]
df.to_csv("movies_genres_en.csv", sep='\t', encoding='utf-8')